### ISSUE TITLE
Chore: Update github repo and Figma community page content

### ISSUE THREAD

**Issue by ryansrofe** [FormidableLabs/FigLog#55]
We need to update the Figma Community page and the GitHub repo with new copy and graphics.

**GitHub Repo**
- update the image at the top to match the image used on the community page (Ryan to provide a new image)
- assess if any updates are needed to the Overview section
- update the Features section
    - 7 changelog types (Coming Soon) -> 7 log types (**New!**)
    - 9 link types (Coming Soon) -> 11 link types (**New!**)
- update any copyright dates such as on the license page?
- add/remove any links or required references for new icon usage

**Figma Community Page** (Ryan can make the edits, need to prep the content)
- update the image at the top to the latest community header image
- open to copy suggestions in the Features section.
    - I feel like instead of a list, we can use h3 headers and supporting text for the specific feature, such as how to add a link, etc
    - 7 changelog types (Coming Soon) -> 7 log types (**New!**)
    - 9 link types (Coming Soon) -> 11 link types (**New!**)
- feedback section content updates
    - any additional branding-related updates from Kat
    - add/remove any links or required references for new icon usage
 - a reminder to update Formidable Figma org content

**Comment by cpresler** [comment]
PR for Repo updates has been pushed.

**Comment by cpresler** [comment]
FigLog Figma Community page content draft here: https://docs.google.com/document/d/1e9nPz0UfBxhZXqX_8XoDnzAUEiwMxSLS7B35S6CuD8Q/edit?usp=sharing

**Comment by cpresler** [comment]
Formidable Figma Community page [header graphic](https://www.figma.com/file/gW23cQidh0SlTulodoyVpX/Figma-Community-Page-Header-Images?type=design&node-id=14%3A3345&mode=design&t=wfdiL6328snD2iJM-1) (transitional brand)

FigLog Community page [updated graphic](https://www.figma.com/file/hpTCPJMc3WvSjSAu1rUfmJ/FigLog-Widget?type=design&node-id=161%3A42760&mode=design&t=VrSXp8xgARrawNbC-1)
